InspectSystem/InspectSystem/Areas/Mobile/Controllers/InspectDocEditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InspectSystem.Models;

namespace InspectSystem.Areas.Mobile.Controllers
{
    [Authorize]
    public class InspectDocEditController : Controller
    {
        private BMEDcontext db = new BMEDcontext();

        // Select class for worker to view DocDetails.
        // GET: Mobile/InspectDocEdit
        public ActionResult Index(int docID)
        {
            var DocDetailList = db.InspectDocDetails.Where(i => i.DocID == docID).ToList();
            var theEditDoc = db.InspectDocs.Find(docID);
            int areaID = theEditDoc.AreaID;
            ViewBag.AreaID = areaID;
            ViewBag.AreaName = theEditDoc.InspectAreas.AreaName;
            ViewBag.DocID = docID;

            /* Find Classes from DocDetails and set values to List<ClassesOfAreas> ClassList. */
            var ClassesOfDocTemp = DocDetailList.GroupBy(c => c.ClassID).Select(g => g.FirstOrDefault()).ToList();
            List<ClassesOfAreas> ClassList = new List<ClassesOfAreas>();
            foreach (var itemClass in ClassesOfDocTemp)
            {
                var addClass = db.ClassesOfAreas.Where(c => c.AreaID == areaID && c.ClassID == itemClass.ClassID).FirstOrDefault();
                ClassList.Add(addClass);
            }
            var ClassesOfAreas = ClassList.OrderBy(c => c.InspectClasses.ClassOrder);

            /* Count errors for every class, and set count result to "CountErrors". */
            foreach (var item in ClassesOfAreas)
            {
                var toFindErrors = DocDetailList.Where(d => d.ClassID == item.ClassID &&
                                                           d.IsFunctional == "n");
                item.CountErrors = toFindErrors.Count();
            }

            return View(ClassesOfAreas.ToList());
        }

        // GET: Mobile/InspectDocEdit/ClassContentOfAreaEdit
        public ActionResult ClassContentOfAreaEdit(int ACID, int docID)
        {
            ViewBag.ClassName = db.ClassesOfAreas.Find(ACID).InspectClasses.ClassName;
            ViewBag.AreaID = db.ClassesOfAreas.Find(ACID).AreaID;
            ViewBag.DocID = docID;
            ViewBag.ACID = ACID;

            /* Find the doc details. */
            var classID = db.ClassesOfAreas.Find(ACID).ClassID;
            var inspectDocDetails = db.InspectDocDetails.Where(i => i.DocID == docID &&
                                                                    i.ClassID == classID);

            /* Get items and fields from DocDetails. */
            ViewBag.itemsByDocDetails = inspectDocDetails.GroupBy(i => i.ItemID)
                                                         .Select(g => g.FirstOrDefault())
                                                         .OrderBy(s => s.ItemOrder).ToList();
            ViewBag.fieldsByDocDetails = inspectDocDetails.ToList();

            InspectDocDetailsViewModels inspectDocDetailsViewModels = new InspectDocDetailsViewModels()
            {
                InspectDocDetails = inspectDocDetails,
            };

            return View(inspectDocDetailsViewModels);
        }

        // GET: Mobile/InspectDocChecker/ClassContentOfArea
        public ActionResult ClassContentOfArea(int ACID, int docID)
        {
            ViewBag.ClassName = db.ClassesOfAreas.Find(ACID).InspectClasses.ClassName;
            ViewBag.AreaID = db.ClassesOfAreas.Find(ACID).AreaID;
            ViewBag.DocID = docID;
            ViewBag.ACID = ACID;

            /* Find the data. */
            var classID = db.ClassesOfAreas.Find(ACID).ClassID;
            var inspectDocDetails = db.InspectDocDetails.Where(i => i.DocID == docID &&
                                                                    i.ClassID == classID);

            /* Get items and fields from DocDetails. */
            ViewBag.itemsByDocDetails = inspectDocDetails.GroupBy(i => i.ItemID)
                                                         .Select(g => g.FirstOrDefault())
                                                         .OrderBy(s => s.ItemOrder).ToList();
            ViewBag.fieldsByDocDetails = inspectDocDetails.ToList();

            InspectDocDetailsViewModels inspectDocDetailsViewModels = new InspectDocDetailsViewModels()
            {
                InspectDocDetails = inspectDocDetails.ToList(),
            };

            return View(inspectDocDetailsViewModels);
        }

        // POST: Mobile/InspectDocEdit/SaveData
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveData(List<InspectDocDetails> inspectDocDetails)
        {
            var areaID = inspectDocDetails.First().AreaID;
            int docID = inspectDocDetails.First().DocID;

            if (ModelState.IsValid)
            {
                foreach (var item in inspectDocDetails)
                {
                    db.Entry(item).State = EntityState.Modified;
                }

                db.SaveChanges();
                TempData["SaveMsg"] = "資料修改完成";
                return RedirectToAction("Index", new { area = "Mobile", DocID = docID });
            }
            TempData["SaveMsg"] = "資料修改失敗";
            return RedirectToAction("Index", new { area = "Mobile", DocID = docID });
        }

        // GET: Mobile/InspectDocEdit/GetFlowList
        public ActionResult GetFlowList(int docID)
        {
            var flowList = db.InspectDocFlows.Where(i => i.DocID == docID).OrderBy(i => i.StepID);
            var findDoc = db.InspectDocs.Find(docID);

            foreach (var item in flowList)
            {
                if (item.StepOwnerID == item.WorkerID)
                {
                    item.StepOwnerName = findDoc.WorkerName;
                }
                else if (item.StepOwnerID == item.CheckerID)
                {
                    item.StepOwnerName = findDoc.CheckerName;
                }
            }

            return View(flowList.ToList());
        }

    }
}

InspectSystem/InspectSystem/Controllers/InspectDocEditController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using InspectSystem.Models;

namespace InspectSystem.Controllers
{
    [Authorize]
    public class InspectDocEditController : Controller
    {
        private BMEDcontext db = new BMEDcontext();

        // GET: InspectDocEdit
        public ActionResult Index(int docID)
        {
            var DocDetailList = db.InspectDocDetails.Where(i => i.DocID == docID).ToList();
            var theEditDoc = db.InspectDocs.Find(docID);
            int areaID = theEditDoc.AreaID;
            ViewBag.AreaID = areaID;
            ViewBag.AreaName = theEditDoc.AreaName;
            ViewBag.DocID = docID;

            /* Find Classes from DocDetails and set values to List<ClassesOfAreas> ClassList. */
            var ClassesOfDocTemp = DocDetailList.GroupBy(c => c.ClassID).Select(g => g.FirstOrDefault()).ToList();
            List<ClassesOfAreas> ClassList = new List<ClassesOfAreas>();
            foreach (var itemClass in ClassesOfDocTemp)
            {
                var addClass = db.ClassesOfAreas.Where(c => c.AreaID == areaID && c.ClassID == itemClass.ClassID).FirstOrDefault();
                ClassList.Add(addClass);
            }
            var ClassesOfAreas = ClassList.OrderBy(c => c.InspectClasses.ClassOrder);

            /* Count errors for every class, and set count result to "CountErrors". */
            foreach (var item in ClassesOfAreas)
            {
                var toFindErrors = DocDetailList.Where(d => d.ClassID == item.ClassID &&
                                                           d.IsFunctional == "n");
                item.CountErrors = toFindErrors.Count();
            }
            return View(ClassesOfAreas.ToList());
        }

        // GET: InspectDocEdit/ClassContentOfArea
        public ActionResult ClassContentOfArea(int ACID, int docID)
        {
            ViewBag.ClassName = db.ClassesOfAreas.Find(ACID).InspectClasses.ClassName;

            /* Find the doc details. */
            var classID = db.ClassesOfAreas.Find(ACID).ClassID;
            var inspectDocDetails = db.InspectDocDetails.Where(i => i.DocID == docID &&
                                                                    i.ClassID == classID);

            /* Get items and fields from DocDetails. */
            ViewBag.itemsByDocDetails = inspectDocDetails.GroupBy(i => i.ItemID)
                                                         .Select(g => g.FirstOrDefault())
                                                         .OrderBy(s => s.ItemOrder).ToList();
            ViewBag.fieldsByDocDetails = inspectDocDetails.ToList();

            InspectDocDetailsViewModels inspectDocDetailsViewModels = new InspectDocDetailsViewModels()
            {
                InspectDocDetails = inspectDocDetails,
            };

            return PartialView(inspectDocDetailsViewModels);
        }

        // POST: InspectDocEdit/SaveData
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult SaveData(List<InspectDocDetails> inspectDocDetails)
        {
            var areaID = inspectDocDetails.First().AreaID;
            int docID = inspectDocDetails.First().DocID;

            if (ModelState.IsValid)
            {
                foreach (var item in inspectDocDetails)
                {
                    db.Entry(item).State = EntityState.Modified;
                }

                db.SaveChanges();
                TempData["SaveMsg"] = "資料修改完成";
                return RedirectToAction("Index", new { DocID = docID });
            }
            TempData["SaveMsg"] = "資料修改失敗";
            return RedirectToAction("Index", new { DocID = docID });
        }

        //GET: InspectDocEdit/CheckValue
        /* Use ajax to check the min and max value for fields. */
        public ActionResult CheckValue(int DocID, int ClassID, int ItemID, int FieldID, string Value)
        {
            /* Get the min and max value for the check field. */
            var SearchDoc = db.InspectDocDetails.Find(DocID, ClassID, ItemID, FieldID);
            var FieldDataType = SearchDoc.DataType;
            float MaxValue = System.Convert.ToSingle(SearchDoc.MaxValue);
            float MinValue = System.Convert.ToSingle(SearchDoc.MinValue);

            /* Only float type will check. */
            string msg = "";
            if (FieldDataType == "float")
            {
                /* Check the input string can be convert to float. */
                if (Single.TryParse(Value, out float inputValue))
                {
                    // Check max and min value, and if doesn't set the min or max value, return nothing.
                    if (inputValue >= MaxValue && MaxValue != 0)
                    {
                        msg = "<span style='color:red'>大於正常數值</span>";
                    }
                    else if (inputValue <= MinValue && MinValue != 0)
                    {
                        msg = "<span style='color:red'>小於正常數值</span>";
                    }
                    else if (MinValue == 0 && MaxValue == 0)
                    {
                        msg = "";
                    }
                    else
                    {
                        msg = "";
                    }
                }
                else
                {
                    msg = "<span style='color:red'>請輸入數字</span>";
                }
            }
            else
            {
                msg = "";
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }

        // GET: InspectDocDetails/DocDetails
        public ActionResult DocDetails(int docID)
        {
            var theEditDoc = db.InspectDocs.Find(docID);
            var DocDetailList = db.InspectDocDetails.Where(i => i.DocID == docID).ToList();
            int areaID = theEditDoc.AreaID;

            ViewBag.AreaID = areaID;
            ViewBag.AreaName = DocDetailList.First().AreaName;
            ViewBag.DocID = docID;

            /* Find Classes from DocDetails and set values to List<ClassesOfAreas> ClassList. */
            var ClassesOfDocTemp = DocDetailList.GroupBy(c => c.ClassID).Select(g => g.FirstOrDefault()).ToList();
            List<ClassesOfAreas> ClassList = new List<ClassesOfAreas>();
            foreach (var itemClass in ClassesOfDocTemp)
            {
                var addClass = db.ClassesOfAreas.Where(c => c.AreaID == areaID && c.ClassID == itemClass.ClassID).FirstOrDefault();
                ClassList.Add(addClass);
            }
            var ClassesOfAreas = ClassList.OrderBy(c => c.InspectClasses.ClassOrder);

            /* Count errors for every class, and set count result to "CountErrors". */
            foreach (var item in ClassesOfAreas)
            {
                var toFindErrors = DocDetailList.Where(d => d.ClassID == item.ClassID &&
                                                           d.IsFunctional == "n");
                item.CountErrors = toFindErrors.Count();
            }
            return View(ClassesOfAreas.ToList());
        }

    }
}

InspectSystem/InspectSystem/Views/InspectDocEdit/DocDetails.cshtml
@model IEnumerable<InspectSystem.Models.ClassesOfAreas>

@Scripts.Render("~/bundles//jquery")
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/DocCheckerDocDetails.js"></script>
<script src="~/Scripts/ScrollToTop.js"></script>
<link rel="stylesheet" type="text/css" href="~/Content/MyStyleForDocDetail.css">

@{
    ViewBag.Title = "詳細內容";
    string backToList = Url.Action("DocListForWorker", "InspectDocChecker").ToString();
}

<style>
    /* Style background-color for modal header and footer. */
    .modal-header, .modal-footer {
        background-color: cornflowerblue;
    }
</style>

<h3 style="font-weight: bold">@ViewBag.AreaName</h3>
<hr />
<div class="container">
    <a class="btn btn-primary" href="@backToList">回到列表</a>
    <a class="btn btn-primary" href="@Url.Action("Index", "InspectDocEdit", new { docID = ViewBag.DocID })">編輯</a>
</div>
<hr />

<div class="container">
    <div class="tab">
        @foreach (var item in Model)
        {
            <button class="tablinks" onclick="openClassContent(event, '@item.ACID', '@ViewBag.DocID')" id="@item.ClassID">
                @item.InspectClasses.ClassName
                @if (item.CountErrors != 0)
                {
                    <span class="circle">@item.CountErrors</span>
                }
            </button>
        }
        <button class="tablinks" id="flowListBtn" onclick="getFlowList(event, '@ViewBag.DocID')">流程資訊</button>
        <!-- Trigger the flowDoc modal with a button -->
        <button class="tablinks" data-toggle="modal" data-target="#flowDocModal" id="flowDocBtn">簽核作業</button>
    </div>

    <div class="tabcontent" id="tabContent">
    </div>
</div>

<div class="container">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#loadingModal" style="display:none" id="loadingBtn">注意事項</button>
    <!-- Loading Modal -->
    <div class="modal fade" id="loadingModal">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header"></div>
                <div class="modal-body">
                    <!-- Loading image for Ajax. -->
                    <div id="loadingIMG" style="text-align: center">
                        <img src="~/Content/ajax-loader.gif" />資料讀取中，請稍後。
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <!-- Flow Doc Modal -->
    <div class="modal fade" id="flowDocModal">
        <div class="modal-dialog model-lg">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.Action("FlowDocEditForWorker", "InspectDocChecker", new { docID = ViewBag.DocID })
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">關閉視窗</button>
                </div>
            </div>
        </div>
    </div>
</div>

<button onclick="topFunction()" id="goToTopBtn" title="Go to top">回頁首</button>

InspectSystem/InspectSystem/Views/InspectDocEdit/Index.cshtml
@model IEnumerable<InspectSystem.Models.ClassesOfAreas>

@Scripts.Render("~/bundles//jquery")
<script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
<script src="~/Scripts/InspectDocEditIndex.js"></script>
<script src="~/Scripts/ScrollToTop.js"></script>
<link rel="stylesheet" href="~/Content/MyStyleForDocDetail.css">

@{
    ViewBag.Title = "內容編輯";

    if (TempData["SaveMsg"] != null)
    {
        <script>
            var message = @Html.Raw(Json.Encode(TempData["SaveMsg"]));
            alert(message);
        </script>
    }
}

<script>
    $(document).ready(function () {
        $("#flowDocBtn").click(function () {
            window.onbeforeunload = null;
        });
    });
</script>

<style>
    /* Style background-color for modal header and footer. */
    .modal-header, .modal-footer {
        background-color: cornflowerblue;
    }
</style>

<h3 style="font-weight: bold">@ViewBag.AreaName</h3>
<hr />
<div class="container">
    <a class="btn btn-primary" href="@Url.Action("DocDetails", "InspectDocEdit", new { docID = ViewBag.DocID })">回詳細內容</a>
</div>
<hr />

<div class="container">
    <div class="tab">
        @foreach (var item in Model)
        {
            <button class="tablinks" onclick="openClassContent(event, '@item.ACID', '@ViewBag.DocID')" id="@item.ClassID">
                @item.InspectClasses.ClassName
                @if (item.CountErrors != 0)
                {
                    <span class="circle">@item.CountErrors</span>
                }
            </button>
        }
        <button class="tablinks" id="flowListBtn" onclick="getFlowList(event, '@ViewBag.DocID')">流程資訊</button>
        <!-- Trigger the flowDoc modal with a button -->
        <button class="tablinks" data-toggle="modal" data-target="#flowDocModal" id="flowDocBtn">簽核作業</button>
    </div>

    <div class="tabcontent" id="tabContent">
    </div>
</div>

<!--Modal for precautions of area.-->
<hr />
<div class="container">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#precautionModal">注意事項</button>

    <!-- Modal -->
    <div class="modal fade" id="precautionModal">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h2 class="modal-title">注意事項</h2>
                </div>
                <div class="modal-body">
                    @Html.Action("AreaPrecautions", "InspectDocDetails", new { areaID = ViewBag.AreaID })
                </div>
                <div class="modal-footer">
                    <div style="text-align:center">
                        <button type="button" class="btn btn-default" data-dismiss="modal">關閉</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <!-- Trigger the modal with a button -->
    <button type="button" class="btn btn-danger btn-lg" data-toggle="modal" data-target="#loadingModal" style="display:none" id="loadingBtn">注意事項</button>
    <!-- Loading Modal -->
    <div class="modal fade" id="loadingModal">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header"></div>
                <div class="modal-body">
                    <!-- Loading image for Ajax. -->
                    <div id="loadingIMG" style="text-align: center">
                        <img src="~/Content/ajax-loader.gif" />資料讀取中，請稍後。
                    </div>
                </div>
                <div class="modal-footer"></div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <!-- Flow Doc Modal -->
    <div class="modal fade" id="flowDocModal">
        <div class="modal-dialog model-lg">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @Html.Action("FlowDoc", "InspectDocChecker", new { docID = ViewBag.DocID })
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">關閉視窗</button>
                </div>
            </div>
        </div>
    </div>
</div>

<button onclick="topFunction()" id="goToTopBtn" title="Go to top">回頁首</button>

InspectSystem/InspectSystem/Views/InspectDocEdit/ViewOfAirCondition.cshtml
@model InspectSystem.Models.InspectDocDetailsViewModels

<script src="~/Scripts/ClassContentOfAreaDocEdit.js"></script>

@{
    ViewBag.Title = "ViewOfAirCondition";
    List<InspectSystem.Models.InspectDocDetails> FieldsOfMostItem = ViewBag.FieldsOfMostItem;
}

<style>
    th, td {
        text-align: center;
    }

    .valueTextBox {
        text-align: left;
        padding: 15px;
    }

    .inputTextOfValue {
        width: 45%;
    }

    .inputTextOfError {
        width: 70%;
    }

    table {
        table-layout: fixed;
        word-break: break-all;
    }

    #sendToChecker {
        position: absolute;
        right: 12px;
    }
</style>

<h3 style="font-weight: bold; padding-left: 10px">@ViewBag.ClassName</h3>
<hr />
@using (Html.BeginForm("SaveData", "InspectDocEdit", FormMethod.Post, new { id = "detailsForm" }))
{
    @Html.AntiForgeryToken()

    var currentItemName = "0";
    int i = 0;
    <div class="container col-md-12">
        <table class="table-bordered">
            <tr class="row">
                <th>
                    <p>運轉機號</p>
                </th>
                @{/* Use foreach to display <th> names. */}
                @foreach (var item in FieldsOfMostItem)
                {
                    if (item.FieldName != null)
                    {
                        <th>
                            <p>@item.FieldName</p>
                        </th>
                    }
                }
                <th>
                    <p>是否正常/</p>
                    <p>錯誤描述</p>
                </th>
            </tr>
            @foreach (var item in Model.InspectItems)
            {
                /* Display the ItemName when ItemName is not the same. */
                if (item.ItemName != currentItemName)
                {
                    <tr class="row">
                        <td>
                            @Html.DisplayFor(modelItem => item.ItemName)
                        </td>
                        @{int countFields = 0;}
                        @foreach (var fieldItem in Model.InspectFields)
                        {
                            /* Display all the FieldName belong the current Item. */
                            if (item.ItemID == fieldItem.ItemID)
                            {
                                foreach (var docItem in Model.InspectDocDetails)
                                {
                                    /* Display textbox or checkbox for all fields. */
                                    if (docItem.ItemID == item.ItemID && docItem.FieldID == fieldItem.FieldID)
                                    {
                                        countFields = countFields + 1;
                                        @Html.Hidden("InspectDocDetails[" + i + "].DocID", docItem.DocID)
                                        @Html.Hidden("InspectDocDetails[" + i + "].AreaID", docItem.AreaID, new { id = "InspectDocDetails[" + i + "].AreaID" })
                                        @Html.Hidden("InspectDocDetails[" + i + "].AreaName", docItem.AreaName)
                                        @Html.Hidden("InspectDocDetails[" + i + "].ClassID", docItem.ClassID, new { id = "InspectDocDetails[" + i + "].ClassID" })
                                        @Html.Hidden("InspectDocDetails[" + i + "].ClassName", docItem.ClassName)
                                        @Html.Hidden("InspectDocDetails[" + i + "].ItemID", docItem.ItemID, new { id = "InspectDocDetails[" + i + "].ItemID" })
                                        @Html.Hidden("InspectDocDetails[" + i + "].ItemName", docItem.ItemName)
                                        @Html.Hidden("InspectDocDetails[" + i + "].FieldID", docItem.FieldID, new { id = "InspectDocDetails[" + i + "].FieldID" })
                                        @Html.Hidden("InspectDocDetails[" + i + "].FieldName", docItem.FieldName)

                                        switch (fieldItem.DataType)
                                        {
                                            case "string":
                                                <td class="valueTextBox">
                                                    @Html.EditorFor(modelItem => docItem.Value, new { htmlAttributes = new { @Name = "InspectDocDetails[" + i + "].Value", @class = "inputTextOfValue" } })
                                                    @Html.ValidationMessage("InspectDocDetails[" + i + "].Value", "", new { @class = "text-danger" })
                                                </td>
                                                break;

                                            case "float":
                                                <td class="valueTextBox">
                                                    @Html.EditorFor(modelItem => docItem.Value, new { htmlAttributes = new { @Name = "InspectDocDetails[" + i + "].Value", @class = "inputTextOfValue inputValue", id = i } })
                                                    @Html.DisplayFor(modelItem => fieldItem.UnitOfData)
                                                    @Html.ValidationMessage("InspectDocDetails[" + i + "].Value", "", new { @class = "text-danger" })
                                                    <br /><span class="@i"></span>
                                                </td>
                                                break;

                                            case "null":
                                                <td></td>
                                                break;

                                            case "boolean":

                                                if (countFields == 1)
                                                {
                                                    for (int j = 1; j < FieldsOfMostItem.Count(); j++)
                                                    {
                                                        <td></td>
                                                    }
                                                }
                                                else if (countFields < FieldsOfMostItem.Count())
                                                {
                                                    <td></td>
                                                }
                                                <td>
                                                    @Html.RadioButtonFor(modelItem => docItem.IsFunctional, true, new { @Name = "InspectDocDetails[" + i + "].IsFunctional" })是
                                                    @Html.RadioButtonFor(modelItem => docItem.IsFunctional, false, new { @Name = "InspectDocDetails[" + i + "].IsFunctional" })否
                                                    @Html.ValidationMessage("InspectDocDetails[" + i + "].IsFunctional", "", new { @class = "text-danger" })
                                                    @Html.TextAreaFor(modelItem => docItem.ErrorDescription, new { @Name = "InspectDocDetails[" + i + "].ErrorDescription", rows = "3" })
                                                </td>
                                                break;
                                        }
                                    }
                                }
                                i++;
                            }
                        }
                    </tr>
                }
                else
                {
                    currentItemName = item.ItemName;
                }
            }
        </table>
        <hr />
        <div>
            <input class="btn btn-primary" type="submit" value="儲存修改資料" />
        </div>
        <hr />
    </div>
}